# NOTE: Minimum dependencies are defined in `pyproject.toml`.
# This file is only used for testing purposes.
# When making changes to minimum dependencies, make sure both this file
# and `pyproject.toml` are consistent with each other.
name: test-environment
channels:
  - conda-forge
dependencies:
  # required dependencies
  - python=3.8
  - python-cmr=0.10.0
  - pqdm=0.1
  - requests=2.26
  - s3fs=2022.11
  - fsspec=2022.11
  - tinynetrc=1.3.1
  - multimethod=1.8
  - importlib-resources=6.3.2
  # test dependencies
  - responses
  - pytest
  - pytest-cov
  - mypy
  - types-requests
  - types-setuptools
  - ruff
  - vcrpy
